sudo: required

services:
  - docker

before_install:
  - docker build -t taman9333/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run taman9333/react-test npm run test -- --coverage

after_success:
  - docker build -t taman9333/multi-client ./client
  - docker build -t taman9333/multi-nginx ./nginx
  - docker build -t taman9333/multi-server ./server
  - docker build -t taman9333/multi-worker ./worker
  # log in to Docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to Docker hyb
  - docker push taman9333/multi-client
  - docker push taman9333/multi-nginx
  - docker push taman9333/multi-server
  - docker push taman9333/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-883808083892
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY